--- tableName: HEALTHEXAM_REG
 create table  HEALTHEXAM_REG( 
 ORG_CODE VARCHAR2(50) ,
 PATIENT_ID VARCHAR2(128) ,
 EVENT_NO VARCHAR2(128) ,
 HEALTH_EXAM_FORM_NO VARCHAR2(128) ,
 HEALTH_RECORD_NO VARCHAR2(17) ,
 CARD_NO VARCHAR2(36) ,
 START_DTIME DATE ,
 EXAM_END_DATE DATE ,
 RETRIEVE_DATE DATE ,
 TOTAL_FEE NUMBER(12,2) ,
 ICD_CODE VARCHAR2(20) ,
 DIAGNOSIS_NAME VARCHAR2(200) ,
 REPORT_TITLE VARCHAR2(256) ,
 EFFECTIVE_DTIME DATE ,
 NAME VARCHAR2(128) ,
 SEX_CODE VARCHAR2(1) ,
 BIRTH_DATE DATE ,
 AGE NUMBER(3) ,
 ADDRESS VARCHAR2(200) ,
 EMPLOYER_NAME VARCHAR2(70) ,
 ID_NO VARCHAR2(18) ,
 OCCUPATION_CODE VARCHAR2(30) ,
 MARRIAGE_CODE VARCHAR2(2) ,
 EXAM_SUMMARY VARCHAR2(4000) ,
 EXAM_CHIEF_DOCTOR VARCHAR2(128) ,
 HEALTH_GUIDE VARCHAR2(4000) ,
 NOTES VARCHAR2(4000) ,
 DIAG_EXPLAN VARCHAR2(4000) ,
 FOOD_GUIDANCE VARCHAR2(4000) ,
 SUMMARIZE_TIME DATE ,
 CHECK_DOCTOR VARCHAR2(128) ,
 CHECK_TIME DATE ,
 PRINT_TIME DATE ); 
comment on table HEALTHEXAM_REG.ORG_CODE is '医疗机构代码';
comment on table HEALTHEXAM_REG.PATIENT_ID is '病人ID';
comment on table HEALTHEXAM_REG.EVENT_NO is '事件号';
comment on table HEALTHEXAM_REG.HEALTH_EXAM_FORM_NO is '健康体检表编号';
comment on table HEALTHEXAM_REG.HEALTH_RECORD_NO is '城乡居民健康档案编号';
comment on table HEALTHEXAM_REG.CARD_NO is '居民健康卡号';
comment on table HEALTHEXAM_REG.START_DTIME is '体检开始时间';
comment on table HEALTHEXAM_REG.EXAM_END_DATE is '体检结束日期';
comment on table HEALTHEXAM_REG.RETRIEVE_DATE is '归档检索日期';
comment on table HEALTHEXAM_REG.TOTAL_FEE is '总费用';
comment on table HEALTHEXAM_REG.ICD_CODE is '主诊断代码';
comment on table HEALTHEXAM_REG.DIAGNOSIS_NAME is '主诊断名称';
comment on table HEALTHEXAM_REG.REPORT_TITLE is '报告的标题';
comment on table HEALTHEXAM_REG.EFFECTIVE_DTIME is '文档创建时间';
comment on table HEALTHEXAM_REG.NAME is '病人的姓名';
comment on table HEALTHEXAM_REG.SEX_CODE is '病人性别代码';
comment on table HEALTHEXAM_REG.BIRTH_DATE is '病人出生日期';
comment on table HEALTHEXAM_REG.AGE is '病人年龄';
comment on table HEALTHEXAM_REG.ADDRESS is '现详细住址';
comment on table HEALTHEXAM_REG.EMPLOYER_NAME is '单位名称';
comment on table HEALTHEXAM_REG.ID_NO is '身份证件号码';
comment on table HEALTHEXAM_REG.OCCUPATION_CODE is '职业类别代码';
comment on table HEALTHEXAM_REG.MARRIAGE_CODE is '婚姻状况代码';
comment on table HEALTHEXAM_REG.EXAM_SUMMARY is '总检结论';
comment on table HEALTHEXAM_REG.EXAM_CHIEF_DOCTOR is '总检医生';
comment on table HEALTHEXAM_REG.HEALTH_GUIDE is '健康指南';
comment on table HEALTHEXAM_REG.NOTES is '备注';
comment on table HEALTHEXAM_REG.DIAG_EXPLAN is '疾病解析';
comment on table HEALTHEXAM_REG.FOOD_GUIDANCE is '饮食建议';
comment on table HEALTHEXAM_REG.SUMMARIZE_TIME is '总检时间';
comment on table HEALTHEXAM_REG.CHECK_DOCTOR is '审核医生';
comment on table HEALTHEXAM_REG.CHECK_TIME is '审核时间';
comment on table HEALTHEXAM_REG.PRINT_TIME is '打印时间';
commit; 


--- tableName: HEALTHEXAM_CATALOG
 create table  HEALTHEXAM_CATALOG( 
 ORG_CODE VARCHAR2(50) ,
 EVENT_NO VARCHAR2(128) ,
 HEALTH_EXAM_FORM_NO VARCHAR2(128) ,
 CATALOG_ID VARCHAR2(128) ,
 CATALOG_NAME VARCHAR2(128) ,
 PERFORMER_DEPT_NAME VARCHAR2(50) ,
 PERFORMER_DOCTOR VARCHAR2(128) ,
 PERFORM_DTIME DATE ,
 SUMMARY VARCHAR2(4000) ); 
comment on table HEALTHEXAM_CATALOG.ORG_CODE is '医疗机构代码';
comment on table HEALTHEXAM_CATALOG.EVENT_NO is '事件号';
comment on table HEALTHEXAM_CATALOG.HEALTH_EXAM_FORM_NO is '健康体检表编号';
comment on table HEALTHEXAM_CATALOG.CATALOG_ID is '体检类别编码';
comment on table HEALTHEXAM_CATALOG.CATALOG_NAME is '体检类别名称';
comment on table HEALTHEXAM_CATALOG.PERFORMER_DEPT_NAME is '执行科室名称';
comment on table HEALTHEXAM_CATALOG.PERFORMER_DOCTOR is '执行医生';
comment on table HEALTHEXAM_CATALOG.PERFORM_DTIME is '执行时间';
comment on table HEALTHEXAM_CATALOG.SUMMARY is '小结';
commit; 


--- tableName: HEALTHEXAM_SUBITEM
 create table  HEALTHEXAM_SUBITEM( 
 ORG_CODE VARCHAR2(50) ,
 HEALTH_EXAM_FORM_NO VARCHAR2(128) ,
 CATALOG_ID VARCHAR2(128) ,
 SERIAL_NO VARCHAR2(128) ,
 CLASS_CODE VARCHAR2(128) ,
 CLASS_NAME VARCHAR2(128) ,
 RESULT_TYPE VARCHAR2(128) ,
 RESULT_TYPE_DESCR VARCHAR2(128) ,
 RESULT_VALUE VARCHAR2(512) ,
 RESULT_UNIT VARCHAR2(20) ,
 NORM_LOWER_LIMIT VARCHAR2(128) ,
 NORM_UPPER_LIMIT VARCHAR2(128) ,
 NORM_VALUE_NOTES VARCHAR2(4000) ,
 RESULT_INTERPRE VARCHAR2(128) ,
 EFFECTIVE_DTIME DATE ,
 EVENT_NO VARCHAR2(128) ,
 RESULT_CODE VARCHAR2(128) ); 
comment on table HEALTHEXAM_SUBITEM.ORG_CODE is '医疗机构代码';
comment on table HEALTHEXAM_SUBITEM.HEALTH_EXAM_FORM_NO is '健康体检表编号';
comment on table HEALTHEXAM_SUBITEM.CATALOG_ID is '所属类别编号';
comment on table HEALTHEXAM_SUBITEM.SERIAL_NO is '子项序号';
comment on table HEALTHEXAM_SUBITEM.CLASS_CODE is '体检项目编码';
comment on table HEALTHEXAM_SUBITEM.CLASS_NAME is '体检项目名称';
comment on table HEALTHEXAM_SUBITEM.RESULT_TYPE is '结果类型';
comment on table HEALTHEXAM_SUBITEM.RESULT_TYPE_DESCR is '结果类型描述';
comment on table HEALTHEXAM_SUBITEM.RESULT_VALUE is '结果值';
comment on table HEALTHEXAM_SUBITEM.RESULT_UNIT is '单位';
comment on table HEALTHEXAM_SUBITEM.NORM_LOWER_LIMIT is '正常参考值下限';
comment on table HEALTHEXAM_SUBITEM.NORM_UPPER_LIMIT is '正常参考值上限';
comment on table HEALTHEXAM_SUBITEM.NORM_VALUE_NOTES is '参考值备注';
comment on table HEALTHEXAM_SUBITEM.RESULT_INTERPRE is '结果值的解释';
comment on table HEALTHEXAM_SUBITEM.EFFECTIVE_DTIME is '该项的创建时间';
comment on table HEALTHEXAM_SUBITEM.EVENT_NO is '事件号';
comment on table HEALTHEXAM_SUBITEM.RESULT_CODE is '结果编码';
commit; 


--- tableName: OUTPATIENT
 create table  OUTPATIENT( 
 ORG_CODE VARCHAR2(50) ,
 PATIENT_ID VARCHAR2(128) ,
 VISIT_ORG_CODE VARCHAR2(50) ,
 OUTPAT_FORM_NO VARCHAR2(128) ,
 VISIT_ORG_NAME VARCHAR2(70) ,
 VISIT_DEPT_NAME VARCHAR2(50) ,
 VISIT_DTIME DATE ,
 REFERRAL_MARK VARCHAR2(1) ,
 HEALTH_SERVICE_DEMAND VARCHAR2(200) ,
 HEALTH_PROBLEM_EVAL VARCHAR2(200) ,
 TREATMENT_PLAN VARCHAR2(200) ,
 OTHER_MEDICAL_TREATMENT VARCHAR2(200) ,
 RESP_DOCTOR_NAME VARCHAR2(128) ,
 SBP NUMBER(3) ,
 DBP NUMBER(3) ,
 DEPT_CODE VARCHAR2(30) ,
 DOCTOR_CODE VARCHAR2(128) ,
 DOCTOR_TITLE_CODE VARCHAR2(128) ,
 REG_TYPE VARCHAR2(128) ,
 SEC_TYPE_CODE VARCHAR2(2) ,
 SEC_NO VARCHAR2(128) ,
 IS_LOCAL_MARK VARCHAR2(1) ,
 STD_DEPT_CODE VARCHAR2(30) ,
 CONSULT_QUESTION VARCHAR2(200) ,
 VALID_TIME_NUM NUMBER(2) ,
 VISIT_FIRST_FLAG VARCHAR2(1) ); 
comment on table OUTPATIENT.ORG_CODE is '医疗机构代码';
comment on table OUTPATIENT.PATIENT_ID is '病人ID';
comment on table OUTPATIENT.VISIT_ORG_CODE is '就诊机构代码';
comment on table OUTPATIENT.OUTPAT_FORM_NO is '门诊记录表编号';
comment on table OUTPATIENT.VISIT_ORG_NAME is '就诊机构名称';
comment on table OUTPATIENT.VISIT_DEPT_NAME is '就诊科室名称';
comment on table OUTPATIENT.VISIT_DTIME is '就诊日期时间';
comment on table OUTPATIENT.REFERRAL_MARK is '转诊标志';
comment on table OUTPATIENT.HEALTH_SERVICE_DEMAND is '卫生服务要求';
comment on table OUTPATIENT.HEALTH_PROBLEM_EVAL is '健康问题评估';
comment on table OUTPATIENT.TREATMENT_PLAN is '处置计划';
comment on table OUTPATIENT.OTHER_MEDICAL_TREATMENT is '其他医学处置';
comment on table OUTPATIENT.RESP_DOCTOR_NAME is '责任医师姓名';
comment on table OUTPATIENT.SBP is '收缩压(mmHg)';
comment on table OUTPATIENT.DBP is '舒张压(mmHg)';
comment on table OUTPATIENT.DEPT_CODE is '院内科室代码';
comment on table OUTPATIENT.DOCTOR_CODE is '医生代码';
comment on table OUTPATIENT.DOCTOR_TITLE_CODE is '医生职称代码';
comment on table OUTPATIENT.REG_TYPE is '挂号类别';
comment on table OUTPATIENT.SEC_TYPE_CODE is '保险类型代码';
comment on table OUTPATIENT.SEC_NO is '医疗保险号';
comment on table OUTPATIENT.IS_LOCAL_MARK is '本地标志';
comment on table OUTPATIENT.STD_DEPT_CODE is '标准科室编码';
comment on table OUTPATIENT.CONSULT_QUESTION is '咨询问题';
comment on table OUTPATIENT.VALID_TIME_NUM is '挂号有效时间';
comment on table OUTPATIENT.VISIT_FIRST_FLAG is '初次就诊';
commit; 


--- tableName: OUTPATIENT_FEE
 create table  OUTPATIENT_FEE( 
 ORG_CODE VARCHAR2(50) ,
 OUTPAT_FORM_NO VARCHAR2(128) ,
 ID VARCHAR2(128) ,
 OUTPAT_FEE_TYPE_CODE VARCHAR2(2) ,
 OUTPAT_FEE_AMOUNT NUMBER(20,2) ,
 PAY_WAY_CODE VARCHAR2(2) ,
 OUTPAT_SETTLE_WAY_CODE VARCHAR2(2) ,
 PRICE_ITEM_LOCAL_CODE VARCHAR2(128) ,
 PRICE_ITEM_LOCAL_NAME VARCHAR2(128) ,
 PRICE_ITEM_STD_CODE VARCHAR2(20) ,
 DEDUCT_FEES_DTIME DATE ,
 SPEC VARCHAR2(20) ,
 UNIT VARCHAR2(20) ,
 PRICE NUMBER(20,4) ,
 QUANTITY NUMBER(12,2) ,
 NOTES VARCHAR2(4000) ,
 SELF_PAYMENT NUMBER(20,2) ,
 APPLY_DEPT_CODE VARCHAR2(30) ,
 APPLY_DEPT_NAME VARCHAR2(50) ,
 APPLY_DOCTOR VARCHAR2(128) ,
 EXEC_DEPT_CODE VARCHAR2(30) ,
 EXEC_DEPT_NAME VARCHAR2(50) ,
 EXEC_MAN VARCHAR2(128) ,
 CHARGES NUMBER(20,2) ,
 INSURANCE_CHARGES NUMBER(20,2) ,
 DERATE_CHARGES NUMBER(20,2) ,
 OPERATOR VARCHAR2(128) ,
 BABAY_FLAG VARCHAR2(1) ); 
comment on table OUTPATIENT_FEE.ORG_CODE is '医疗机构代码';
comment on table OUTPATIENT_FEE.OUTPAT_FORM_NO is '门诊记录表编号';
comment on table OUTPATIENT_FEE.ID is '序列号';
comment on table OUTPATIENT_FEE.OUTPAT_FEE_TYPE_CODE is '门诊费用分类代码';
comment on table OUTPATIENT_FEE.OUTPAT_FEE_AMOUNT is '门诊费用金额（元）';
comment on table OUTPATIENT_FEE.PAY_WAY_CODE is '医疗付款方式代码';
comment on table OUTPATIENT_FEE.OUTPAT_SETTLE_WAY_CODE is '门诊费用结算方式代码';
comment on table OUTPATIENT_FEE.PRICE_ITEM_LOCAL_CODE is '价项院内代码';
comment on table OUTPATIENT_FEE.PRICE_ITEM_LOCAL_NAME is '价项院内名称';
comment on table OUTPATIENT_FEE.PRICE_ITEM_STD_CODE is '价项标准代码';
comment on table OUTPATIENT_FEE.DEDUCT_FEES_DTIME is '扣费日期';
comment on table OUTPATIENT_FEE.SPEC is '规格';
comment on table OUTPATIENT_FEE.UNIT is '单位';
comment on table OUTPATIENT_FEE.PRICE is '单价';
comment on table OUTPATIENT_FEE.QUANTITY is '数量';
comment on table OUTPATIENT_FEE.NOTES is '备注';
comment on table OUTPATIENT_FEE.SELF_PAYMENT is '个人承担费用金额';
comment on table OUTPATIENT_FEE.APPLY_DEPT_CODE is '开单科室代码';
comment on table OUTPATIENT_FEE.APPLY_DEPT_NAME is '开单科室名称';
comment on table OUTPATIENT_FEE.APPLY_DOCTOR is '开单医生';
comment on table OUTPATIENT_FEE.EXEC_DEPT_CODE is '执行科室代码';
comment on table OUTPATIENT_FEE.EXEC_DEPT_NAME is '执行科室名称';
comment on table OUTPATIENT_FEE.EXEC_MAN is '执行医生';
comment on table OUTPATIENT_FEE.CHARGES is '自付';
comment on table OUTPATIENT_FEE.INSURANCE_CHARGES is '医保金额';
comment on table OUTPATIENT_FEE.DERATE_CHARGES is '减免金额';
comment on table OUTPATIENT_FEE.OPERATOR is '操作员';
comment on table OUTPATIENT_FEE.BABAY_FLAG is '婴儿标志';
commit; 


--- tableName: OUTPATIENT_DRUG
 create table  OUTPATIENT_DRUG( 
 ORG_CODE VARCHAR2(50) ,
 OUTPAT_FORM_NO VARCHAR2(128) ,
 ID VARCHAR2(128) ,
 CN_MEDICINE_TYPE_CODE VARCHAR2(1) ,
 DRUG_TYPE_CODE VARCHAR2(7) ,
 DRUG_LOCAL_CODE VARCHAR2(50) ,
 DRUG_NAME VARCHAR2(200) ,
 DRUG_FORM_CODE VARCHAR2(3) ,
 DRUG_USING_DAYS NUMBER(5) ,
 DRUG_USING_FREQ VARCHAR2(20) ,
 DRUG_DOSE_UNIT VARCHAR2(50) ,
 DRUG_PER_DOSE NUMBER(7,2) ,
 DRUG_TOTAL_DOSE NUMBER(20,4) ,
 DRUG_ROUTE_CODE VARCHAR2(3) ,
 DRUG_STOP_DTIME DATE ,
 DRUG_STD_NAME VARCHAR2(200) ,
 DRUG_STD_CODE VARCHAR2(50) ,
 DRUG_TOTAL_UNIT VARCHAR2(128) ,
 SPEC VARCHAR2(50) ,
 GROUP_NO VARCHAR2(128) ,
 DRUG_START_DTIME DATE ,
 DISPENSING_DTIME DATE ,
 NOTES VARCHAR2(4000) ,
 DDD_VALUE NUMBER(20,4) ,
 ANTIBACTERIAL_FLAG VARCHAR2(1) ,
 CRUCIAL_DRUG_NAME VARCHAR2(2000) ,
 CRUCIAL_DRUG_USAGE VARCHAR2(4000) ,
 PRESCRIBE_NO VARCHAR2(200) ,
 DRUG_ADVERSE_REACTION VARCHAR2(4000) ); 
comment on table OUTPATIENT_DRUG.ORG_CODE is '医疗机构代码';
comment on table OUTPATIENT_DRUG.OUTPAT_FORM_NO is '门诊记录表编号';
comment on table OUTPATIENT_DRUG.ID is '序列号';
comment on table OUTPATIENT_DRUG.CN_MEDICINE_TYPE_CODE is '中药类别代码';
comment on table OUTPATIENT_DRUG.DRUG_TYPE_CODE is '药物类型代码';
comment on table OUTPATIENT_DRUG.DRUG_LOCAL_CODE is '药物院内编码';
comment on table OUTPATIENT_DRUG.DRUG_NAME is '药物名称';
comment on table OUTPATIENT_DRUG.DRUG_FORM_CODE is '药物剂型代码';
comment on table OUTPATIENT_DRUG.DRUG_USING_DAYS is '用药天数';
comment on table OUTPATIENT_DRUG.DRUG_USING_FREQ is '药物使用频率';
comment on table OUTPATIENT_DRUG.DRUG_DOSE_UNIT is '药物使用剂量单位';
comment on table OUTPATIENT_DRUG.DRUG_PER_DOSE is '药物使用次剂量';
comment on table OUTPATIENT_DRUG.DRUG_TOTAL_DOSE is '药物使用总剂量';
comment on table OUTPATIENT_DRUG.DRUG_ROUTE_CODE is '药物使用途径代码';
comment on table OUTPATIENT_DRUG.DRUG_STOP_DTIME is '用药停止日期时间';
comment on table OUTPATIENT_DRUG.DRUG_STD_NAME is '药物标准名称';
comment on table OUTPATIENT_DRUG.DRUG_STD_CODE is '药物标准编码';
comment on table OUTPATIENT_DRUG.DRUG_TOTAL_UNIT is '药物使用-总剂量单位';
comment on table OUTPATIENT_DRUG.SPEC is '规格';
comment on table OUTPATIENT_DRUG.GROUP_NO is '成组号（0-无分组）';
comment on table OUTPATIENT_DRUG.DRUG_START_DTIME is '开始时间';
comment on table OUTPATIENT_DRUG.DISPENSING_DTIME is '发药时间';
comment on table OUTPATIENT_DRUG.NOTES is '备注';
comment on table OUTPATIENT_DRUG.DDD_VALUE is 'DDD值/最小剂量';
comment on table OUTPATIENT_DRUG.ANTIBACTERIAL_FLAG is '抗菌药物标志';
comment on table OUTPATIENT_DRUG.CRUCIAL_DRUG_NAME is '关键药物名称';
comment on table OUTPATIENT_DRUG.CRUCIAL_DRUG_USAGE is '关键药物用法';
comment on table OUTPATIENT_DRUG.PRESCRIBE_NO is '处方编号';
comment on table OUTPATIENT_DRUG.DRUG_ADVERSE_REACTION is '药物不良反应情况';
commit; 


--- tableName: OUTPATIENT_DIAG
 create table  OUTPATIENT_DIAG( 
 ORG_CODE VARCHAR2(50) ,
 OUTPAT_FORM_NO VARCHAR2(128) ,
 DIAGNOSIS_ID VARCHAR2(128) ,
 OUTPAT_DIAG_NAME VARCHAR2(200) ,
 OUTPAT_DIAG_CODE VARCHAR2(20) ,
 DIAG_DATE DATE ,
 DIAG_TYPE_CODE VARCHAR2(128) ,
 INFECT_FLAG VARCHAR2(1) ,
 INFECT_REPORT_FLAG VARCHAR2(1) ); 
comment on table OUTPATIENT_DIAG.ORG_CODE is '医疗机构代码';
comment on table OUTPATIENT_DIAG.OUTPAT_FORM_NO is '门诊记录表编号';
comment on table OUTPATIENT_DIAG.DIAGNOSIS_ID is '诊断序列号';
comment on table OUTPATIENT_DIAG.OUTPAT_DIAG_NAME is '门诊诊断名称';
comment on table OUTPATIENT_DIAG.OUTPAT_DIAG_CODE is '门诊诊断代码';
comment on table OUTPATIENT_DIAG.DIAG_DATE is '诊断日期';
comment on table OUTPATIENT_DIAG.DIAG_TYPE_CODE is '诊断类型代码';
comment on table OUTPATIENT_DIAG.INFECT_FLAG is '传染标志';
comment on table OUTPATIENT_DIAG.INFECT_REPORT_FLAG is '传染上报标志';
commit; 


--- tableName: OUTPATIENT_SYMP
 create table  OUTPATIENT_SYMP( 
 ORG_CODE VARCHAR2(50) ,
 OUTPAT_FORM_NO VARCHAR2(128) ,
 SYMPTOM_ID VARCHAR2(128) ,
 SYMPTOM_NAME VARCHAR2(200) ,
 SYMPTOM_CODE VARCHAR2(50) ,
 ONSET_DTIME DATE ,
 SYMP_DURATION_MINS NUMBER(3) ); 
comment on table OUTPATIENT_SYMP.ORG_CODE is '医疗机构代码';
comment on table OUTPATIENT_SYMP.OUTPAT_FORM_NO is '门诊记录表编号';
comment on table OUTPATIENT_SYMP.SYMPTOM_ID is '症状序列号';
comment on table OUTPATIENT_SYMP.SYMPTOM_NAME is '症状名称';
comment on table OUTPATIENT_SYMP.SYMPTOM_CODE is '症状代码';
comment on table OUTPATIENT_SYMP.ONSET_DTIME is '发病日期时间';
comment on table OUTPATIENT_SYMP.SYMP_DURATION_MINS is '症状持续时间（min)';
commit; 


--- tableName: OUTPATIENT_REFERRAL
 create table  OUTPATIENT_REFERRAL( 
 ORG_CODE VARCHAR2(50) ,
 OUTPAT_FORM_NO VARCHAR2(128) ,
 CHANGE_NO VARCHAR2(128) ,
 REFERFROM_ORG_NAME VARCHAR2(70) ,
 REFERFROM_ORG_CODE VARCHAR2(50) ,
 REFERFROM_DEPT_NAME VARCHAR2(50) ,
 REFERTO_ORG_NAME VARCHAR2(70) ,
 REFERTO_ORG_CODE VARCHAR2(50) ,
 REFERTO_DEPT_NAME VARCHAR2(50) ,
 REFERRAL_RECORDS VARCHAR2(4000) ,
 REFERRAL_DATE DATE ,
 REFERRAL_REASON VARCHAR2(100) ,
 TREATMENT_PROPOSAL VARCHAR2(200) ,
 MENTAL_REHAB_MEANS_GUIDE VARCHAR2(100) ); 
comment on table OUTPATIENT_REFERRAL.ORG_CODE is '医疗机构代码';
comment on table OUTPATIENT_REFERRAL.OUTPAT_FORM_NO is '门诊记录表编号';
comment on table OUTPATIENT_REFERRAL.CHANGE_NO is '转诊记录表单号';
comment on table OUTPATIENT_REFERRAL.REFERFROM_ORG_NAME is '转出医疗机构名称';
comment on table OUTPATIENT_REFERRAL.REFERFROM_ORG_CODE is '转出医疗机构代码';
comment on table OUTPATIENT_REFERRAL.REFERFROM_DEPT_NAME is '转出医疗机构科室名称';
comment on table OUTPATIENT_REFERRAL.REFERTO_ORG_NAME is '转入医疗机构名称';
comment on table OUTPATIENT_REFERRAL.REFERTO_ORG_CODE is '转入医疗机构代码';
comment on table OUTPATIENT_REFERRAL.REFERTO_DEPT_NAME is '转入机构科室名称';
comment on table OUTPATIENT_REFERRAL.REFERRAL_RECORDS is '转诊记录';
comment on table OUTPATIENT_REFERRAL.REFERRAL_DATE is '转诊日期';
comment on table OUTPATIENT_REFERRAL.REFERRAL_REASON is '转诊原因';
comment on table OUTPATIENT_REFERRAL.TREATMENT_PROPOSAL is '治疗方案';
comment on table OUTPATIENT_REFERRAL.MENTAL_REHAB_MEANS_GUIDE is '康复措施指导';
commit; 


--- tableName: EDS_DISP_PRES_MASTER
 create table  EDS_DISP_PRES_MASTER( 
 ORG_CODE VARCHAR2(50) ,
 PRESCRIBE_NO VARCHAR2(200) ,
 PRES_CLASS_CODE VARCHAR2(1) ,
 PATIENT_ID VARCHAR2(128) ,
 OUTPAT_FORM_NO VARCHAR2(128) ,
 NAME VARCHAR2(128) ,
 SEX_CODE VARCHAR2(1) ,
 AGE_YEAR NUMBER(3) ,
 AGE_MONTH VARCHAR2(8) ,
 DIAGNOSIS_CODE VARCHAR2(20) ,
 DIAGNOSIS_NAME VARCHAR2(200) ,
 TCM_DIAGNOSIS_CODE VARCHAR2(20) ,
 TCM_SYNDROME_CODE VARCHAR2(20) ,
 THERAPEUTIC_PRINCIPLES VARCHAR2(2000) ,
 PRES_DESCRIBE VARCHAR2(4000) ,
 TCM_DECOC_PIECE_METHOD VARCHAR2(2000) ,
 TCM_USE_METHOD VARCHAR2(200) ,
 COST NUMBER(20,2) ,
 TERM_COUNT NUMBER(5) ,
 APPLY_DEPT_CODE VARCHAR2(200) ,
 APPLY_TIME DATE ,
 APPLY_OPERATOR VARCHAR2(2000) ,
 PERFORM_OPERATOR VARCHAR2(128) ,
 PERFORM_DEPT_CODE VARCHAR2(50) ,
 PERFORM_DTIME DATE ,
 AUDIT_OPERATOR VARCHAR2(2000) ,
 AUDIT_TIME DATE ,
 DISTRIBUTE_OPERATOR VARCHAR2(128) ,
 CHECK_OPERATOR VARCHAR2(128) ,
 DISPENSE_OPERATOR VARCHAR2(128) ); 
comment on table EDS_DISP_PRES_MASTER.ORG_CODE is '医疗机构代码';
comment on table EDS_DISP_PRES_MASTER.PRESCRIBE_NO is '处方编号';
comment on table EDS_DISP_PRES_MASTER.PRES_CLASS_CODE is '处方类别代码（1.中药饮片处方 2.中成药处方 3.西药处方）';
comment on table EDS_DISP_PRES_MASTER.PATIENT_ID is '病人ID';
comment on table EDS_DISP_PRES_MASTER.OUTPAT_FORM_NO is '门急诊号';
comment on table EDS_DISP_PRES_MASTER.NAME is '患者姓名';
comment on table EDS_DISP_PRES_MASTER.SEX_CODE is '性别代码';
comment on table EDS_DISP_PRES_MASTER.AGE_YEAR is '年龄（岁）';
comment on table EDS_DISP_PRES_MASTER.AGE_MONTH is '年龄（月）';
comment on table EDS_DISP_PRES_MASTER.DIAGNOSIS_CODE is '西医诊断编码';
comment on table EDS_DISP_PRES_MASTER.DIAGNOSIS_NAME is '西医诊断名称';
comment on table EDS_DISP_PRES_MASTER.TCM_DIAGNOSIS_CODE is '中医病名代码';
comment on table EDS_DISP_PRES_MASTER.TCM_SYNDROME_CODE is '中医证候代码';
comment on table EDS_DISP_PRES_MASTER.THERAPEUTIC_PRINCIPLES is '治则治法';
comment on table EDS_DISP_PRES_MASTER.PRES_DESCRIBE is '处方说明';
comment on table EDS_DISP_PRES_MASTER.TCM_DECOC_PIECE_METHOD is '中药煎煮方法';
comment on table EDS_DISP_PRES_MASTER.TCM_USE_METHOD is '中药用药方法';
comment on table EDS_DISP_PRES_MASTER.COST is '金额';
comment on table EDS_DISP_PRES_MASTER.TERM_COUNT is '处方有效天数';
comment on table EDS_DISP_PRES_MASTER.APPLY_DEPT_CODE is '处方开立科室名称';
comment on table EDS_DISP_PRES_MASTER.APPLY_TIME is '处方开立日期';
comment on table EDS_DISP_PRES_MASTER.APPLY_OPERATOR is '处方开立医师签名';
comment on table EDS_DISP_PRES_MASTER.PERFORM_OPERATOR is '执行人';
comment on table EDS_DISP_PRES_MASTER.PERFORM_DEPT_CODE is '执行科室代码';
comment on table EDS_DISP_PRES_MASTER.PERFORM_DTIME is '执行时间';
comment on table EDS_DISP_PRES_MASTER.AUDIT_OPERATOR is '处方审核医师';
comment on table EDS_DISP_PRES_MASTER.AUDIT_TIME is '审核日期';
comment on table EDS_DISP_PRES_MASTER.DISTRIBUTE_OPERATOR is '处方调配医师';
comment on table EDS_DISP_PRES_MASTER.CHECK_OPERATOR is '处方核对医师';
comment on table EDS_DISP_PRES_MASTER.DISPENSE_OPERATOR is '处方发药医师';
commit; 


--- tableName: EDS_OUTPAT_MEDICAL_RECORD
 create table  EDS_OUTPAT_MEDICAL_RECORD( 
 ORG_CODE VARCHAR2(128) ,
 PATIENT_ID VARCHAR2(128) ,
 OUTPAT_FORM_NO VARCHAR2(128) ,
 DEPT_CODE VARCHAR2(30) ,
 DEPT_NAME VARCHAR2(128) ,
 NAME VARCHAR2(128) ,
 SEX_CODE VARCHAR2(1) ,
 BIRTH_DATE DATE ,
 AGE_YEAR NUMBER(3) ,
 AGE_MONTH VARCHAR2(8) ,
 ALLERGY_HISTORY_FLAG VARCHAR2(1) ,
 ALLERGY_HISTORY VARCHAR2(100) ,
 VISIT_DTIME DATE ,
 FIRST_FLAG VARCHAR2(1) ,
 CHIEF_COMPLAINTS VARCHAR2(2000) ,
 CURRENT_DISEASE VARCHAR2(2000) ,
 DISEASE_HISTORY VARCHAR2(2000) ,
 PHYSICAL_EXAMINATION VARCHAR2(4000) ,
 TCM_OBSERVE VARCHAR2(4000) ,
 ASSIST_EXAM_ITEM VARCHAR2(100) ,
 ASSIST_EXAM_RESULT VARCHAR2(1000) ,
 DIALECTICAL_BASIS VARCHAR2(4000) ,
 THERAPEUTIC_PRINCIPLES VARCHAR2(2000) ,
 DOCTOR_SIGNATURE VARCHAR2(2000) ,
 NOTES VARCHAR2(4000) ); 
comment on table EDS_OUTPAT_MEDICAL_RECORD.ORG_CODE is '医疗机构代码';
comment on table EDS_OUTPAT_MEDICAL_RECORD.PATIENT_ID is '病人ID';
comment on table EDS_OUTPAT_MEDICAL_RECORD.OUTPAT_FORM_NO is '门（急）诊号';
comment on table EDS_OUTPAT_MEDICAL_RECORD.DEPT_CODE is '科室编码';
comment on table EDS_OUTPAT_MEDICAL_RECORD.DEPT_NAME is '科室名称';
comment on table EDS_OUTPAT_MEDICAL_RECORD.NAME is '患者姓名';
comment on table EDS_OUTPAT_MEDICAL_RECORD.SEX_CODE is '性别代码';
comment on table EDS_OUTPAT_MEDICAL_RECORD.BIRTH_DATE is '出生日期';
comment on table EDS_OUTPAT_MEDICAL_RECORD.AGE_YEAR is '年龄（岁）';
comment on table EDS_OUTPAT_MEDICAL_RECORD.AGE_MONTH is '年龄（月）';
comment on table EDS_OUTPAT_MEDICAL_RECORD.ALLERGY_HISTORY_FLAG is '过敏史标志';
comment on table EDS_OUTPAT_MEDICAL_RECORD.ALLERGY_HISTORY is '过敏史';
comment on table EDS_OUTPAT_MEDICAL_RECORD.VISIT_DTIME is '就诊日期时间';
comment on table EDS_OUTPAT_MEDICAL_RECORD.FIRST_FLAG is '初诊标志代码';
comment on table EDS_OUTPAT_MEDICAL_RECORD.CHIEF_COMPLAINTS is '主诉';
comment on table EDS_OUTPAT_MEDICAL_RECORD.CURRENT_DISEASE is '现病史';
comment on table EDS_OUTPAT_MEDICAL_RECORD.DISEASE_HISTORY is '既往史';
comment on table EDS_OUTPAT_MEDICAL_RECORD.PHYSICAL_EXAMINATION is '体格检查';
comment on table EDS_OUTPAT_MEDICAL_RECORD.TCM_OBSERVE is '中医（四诊）观察结果';
comment on table EDS_OUTPAT_MEDICAL_RECORD.ASSIST_EXAM_ITEM is '辅助检查项目';
comment on table EDS_OUTPAT_MEDICAL_RECORD.ASSIST_EXAM_RESULT is '辅助检查结果';
comment on table EDS_OUTPAT_MEDICAL_RECORD.DIALECTICAL_BASIS is '辨证依据';
comment on table EDS_OUTPAT_MEDICAL_RECORD.THERAPEUTIC_PRINCIPLES is '治则治法';
comment on table EDS_OUTPAT_MEDICAL_RECORD.DOCTOR_SIGNATURE is '医师签名';
comment on table EDS_OUTPAT_MEDICAL_RECORD.NOTES is '备注';
commit; 


--- tableName: EDS_EM_OBSERVATION_MED_RECORD
 create table  EDS_EM_OBSERVATION_MED_RECORD( 
 ORG_CODE VARCHAR2(128) ,
 PATIENT_ID VARCHAR2(128) ,
 OUTPAT_FORM_NO VARCHAR2(128) ,
 DEPT_CODE VARCHAR2(30) ,
 DEPT_NAME VARCHAR2(128) ,
 NAME VARCHAR2(128) ,
 SEX_CODE VARCHAR2(1) ,
 BIRTH_DATE DATE ,
 AGE_YEAR NUMBER(3) ,
 AGE_MONTH VARCHAR2(8) ,
 ALLERGY_HISTORY_FLAG VARCHAR2(1) ,
 ALLERGY_HISTORY VARCHAR2(100) ,
 VISIT_DTIME DATE ,
 FIRST_FLAG VARCHAR2(1) ,
 OBSERVE_START_TIME DATE ,
 CHIEF_COMPLAINTS VARCHAR2(2000) ,
 CURRENT_DISEASE VARCHAR2(2000) ,
 DISEASE_HISTORY VARCHAR2(2000) ,
 PHYSICAL_EXAMINATION VARCHAR2(4000) ,
 TCM_OBSERVE VARCHAR2(2000) ,
 ASSIST_EXAM_ITEM VARCHAR2(100) ,
 ASSIST_EXAM_RESULT VARCHAR2(1000) ,
 DIALECTICAL_BASIS VARCHAR2(4000) ,
 THERAPEUTIC_PRINCIPLES VARCHAR2(2000) ,
 PROGRESS_RECORD VARCHAR2(4000) ,
 RESCUE_START_TIME DATE ,
 RESCUE_END_TIME DATE ,
 RESCUE_RECORD VARCHAR2(2000) ,
 OPERATION_COUNT NUMBER(20,0) ,
 OPERATION_RECORD_TIME DATE ,
 OPERATION_NOTE VARCHAR2(4000) ,
 PARTICIPATORS VARCHAR2(4000) ,
 TITLE_CODE VARCHAR2(128) ,
 TRACE_CODE VARCHAR2(1) ,
 CREATOR VARCHAR2(2000) ,
 NOTES VARCHAR2(4000) ); 
comment on table EDS_EM_OBSERVATION_MED_RECORD.ORG_CODE is '医疗机构代码';
comment on table EDS_EM_OBSERVATION_MED_RECORD.PATIENT_ID is '病人ID';
comment on table EDS_EM_OBSERVATION_MED_RECORD.OUTPAT_FORM_NO is '门（急）诊号';
comment on table EDS_EM_OBSERVATION_MED_RECORD.DEPT_CODE is '科室编码';
comment on table EDS_EM_OBSERVATION_MED_RECORD.DEPT_NAME is '科室名称';
comment on table EDS_EM_OBSERVATION_MED_RECORD.NAME is '患者姓名';
comment on table EDS_EM_OBSERVATION_MED_RECORD.SEX_CODE is '性别代码';
comment on table EDS_EM_OBSERVATION_MED_RECORD.BIRTH_DATE is '出生日期';
comment on table EDS_EM_OBSERVATION_MED_RECORD.AGE_YEAR is '年龄（岁）';
comment on table EDS_EM_OBSERVATION_MED_RECORD.AGE_MONTH is '年龄（月）';
comment on table EDS_EM_OBSERVATION_MED_RECORD.ALLERGY_HISTORY_FLAG is '过敏史标志';
comment on table EDS_EM_OBSERVATION_MED_RECORD.ALLERGY_HISTORY is '过敏史';
comment on table EDS_EM_OBSERVATION_MED_RECORD.VISIT_DTIME is '就诊日期时间';
comment on table EDS_EM_OBSERVATION_MED_RECORD.FIRST_FLAG is '初诊标志代码';
comment on table EDS_EM_OBSERVATION_MED_RECORD.OBSERVE_START_TIME is '收入观察室日期时间';
comment on table EDS_EM_OBSERVATION_MED_RECORD.CHIEF_COMPLAINTS is '主诉';
comment on table EDS_EM_OBSERVATION_MED_RECORD.CURRENT_DISEASE is '现病史';
comment on table EDS_EM_OBSERVATION_MED_RECORD.DISEASE_HISTORY is '既往史';
comment on table EDS_EM_OBSERVATION_MED_RECORD.PHYSICAL_EXAMINATION is '体格检查';
comment on table EDS_EM_OBSERVATION_MED_RECORD.TCM_OBSERVE is '中医（四诊）观察结果';
comment on table EDS_EM_OBSERVATION_MED_RECORD.ASSIST_EXAM_ITEM is '辅助检查项目';
comment on table EDS_EM_OBSERVATION_MED_RECORD.ASSIST_EXAM_RESULT is '辅助检查结果';
comment on table EDS_EM_OBSERVATION_MED_RECORD.DIALECTICAL_BASIS is '辨证依据';
comment on table EDS_EM_OBSERVATION_MED_RECORD.THERAPEUTIC_PRINCIPLES is '治则治法';
comment on table EDS_EM_OBSERVATION_MED_RECORD.PROGRESS_RECORD is '急诊留观病程记录';
comment on table EDS_EM_OBSERVATION_MED_RECORD.RESCUE_START_TIME is '抢救开始日期时间';
comment on table EDS_EM_OBSERVATION_MED_RECORD.RESCUE_END_TIME is '抢救结束日期时间';
comment on table EDS_EM_OBSERVATION_MED_RECORD.RESCUE_RECORD is '急诊抢救记录';
comment on table EDS_EM_OBSERVATION_MED_RECORD.OPERATION_COUNT is '手术及操作次数';
comment on table EDS_EM_OBSERVATION_MED_RECORD.OPERATION_RECORD_TIME is '记录日期时间';
comment on table EDS_EM_OBSERVATION_MED_RECORD.OPERATION_NOTE is '注意事项';
comment on table EDS_EM_OBSERVATION_MED_RECORD.PARTICIPATORS is '参加抢救人员名单';
comment on table EDS_EM_OBSERVATION_MED_RECORD.TITLE_CODE is '专业技术职务类别代码';
comment on table EDS_EM_OBSERVATION_MED_RECORD.TRACE_CODE is '患者去向代码';
comment on table EDS_EM_OBSERVATION_MED_RECORD.CREATOR is '医师签名';
comment on table EDS_EM_OBSERVATION_MED_RECORD.NOTES is '备注';
commit; 


